ISSUE-9: Clean individual files when CreateSubdirectories is false
FrendsPlatform/Frends.Files pull request #10
Opened 2022-10-13 06:23 UTC by Svenskapojkarna

2022-10-13 08:54 UTC, RikuVirtanen requested changes

2022-10-13 08:54 UTC, RikuVirtanen commented on Frends.Files.LocalBackup/Frends.Files.LocalBackup/LocalBackup.cs
> +                foreach (var dir in Directory.GetDirectories(backupDirectory))
Is it possible in Linux that the GetDirectories() method returns also dirs: '.' and '..'? If so there should be a check that those are not deleted.

2022-10-13 08:54 UTC, RikuVirtanen commented on Frends.Files.LocalBackup/Frends.Files.LocalBackup/LocalBackup.cs
>              else
Same thing in the else path.

2022-11-17 13:43 UTC, Svenskapojkarna commented on Frends.Files.LocalBackup/Frends.Files.LocalBackup/LocalBackup.cs
> +                foreach (var dir in Directory.GetDirectories(backupDirectory))
Seems like they don't. Method only returns directories in the directory.

2022-11-17 13:43 UTC, Svenskapojkarna commented on Frends.Files.LocalBackup/Frends.Files.LocalBackup/LocalBackup.cs
>              else
Same thing here.

2022-11-23 08:02 UTC, RikuVirtanen approved these changes

2022-11-23 08:02 UTC, merged